name: redu-clean2

channels:
  - astropy
  - mwcraig

dependencies:
  - appnope
  - astropy
  - astroscrappy
  - backports
  - backports_abc
  - bokeh
  - ccdproc
  - chest
  - cloudpickle
  - configparser
  - cycler
  - dask
  - decorator
  - entrypoints
  - freetype
  - functools32
  - futures
  - get_terminal_size
  - heapdict
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jbig
  - jinja2
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - libpng
  - libtiff
  - locket
  - markupsafe
  - matplotlib
  - mistune
  - mkl
  - nbconvert
  - nbformat
  - networkx
  - notebook
  - numpy
  - openssl
  - pandas
  - partd
  - path.py
  - pathlib2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - ptyprocess
  - pygments
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - python.app
  - pytz
  - pyyaml
  - pyzmq
  - qt
  - readline
  - reproject
  - requests
  - scikit-image
  - scipy
  - setuptools
  - simplegeneric
  - singledispatch
  - sip
  - six
  - sqlite
  - ssl_match_hostname
  - terminado
  - tk
  - toolz
  - tornado
  - traitlets
  - wheel
  - xz
  - yaml
  - zlib
  - msumastro
  - pip:
    - backports-abc
    - backports.shutil-get-terminal-size
    - backports.ssl-match-hostname
    - ipython-genutils
    - jupyter-client
    - jupyter-core
